SELECT
  HRE_NOTIFY_ID,
  HRE_NOTIFY_USER_ID,
  HRE_NOTIFY_TEMPLATE,
  HRE_NOTIFY_TIMESTAMP,
  HRE_NOTIFY_CONTEXT,
  HRE_NOTIFY_STATUS_CODE,
  HRE_NOTIFY_STATUS_DESC
FROM
  MFOREST.HRE_NOTIFY
WHERE
  HRE_NOTIFY_ID = :HRE_NOTIFY_ID
