UPDATE
  MFOREST.HRE_NOTIFY
SET
  HRE_NOTIFY_CONTEXT = :HRE_NOTIFY_CONTEXT,
  HRE_NOTIFY_STATUS_CODE = :HRE_NOTIFY_STATUS_CODE,
  HRE_NOTIFY_STATUS_DESC = :HRE_NOTIFY_STATUS_DESC
WHERE
  HRE_NOTIFY_ID = :HRE_NOTIFY_ID AND
  HRE_NOTIFY_USER_ID = :HRE_NOTIFY_USER_ID AND
  HRE_NOTIFY_TEMPLATE = :HRE_NOTIFY_TEMPLATE AND
  HRE_NOTIFY_TIMESTAMP = TO_DATE(:HRE_NOTIFY_TIMESTAMP, 'yyyy-mm-dd hh24:mi:ss')
