DROP TABLE HRE_NOTIFY;

CREATE TABLE HRE_NOTIFY (
  HRE_NOTIFY_ID          VARCHAR2(36) NOT NULL,
  HRE_NOTIFY_USER_ID     NUMBER(10,0) NOT NULL,
  HRE_NOTIFY_TEMPLATE    VARCHAR2(512) NOT NULL,
  HRE_NOTIFY_TIMESTAMP   DATE NOT NULL,
  HRE_NOTIFY_CONTEXT     CLOB NOT NULL,
  HRE_NOTIFY_STATUS_CODE VARCHAR2(10) DEFAULT NULL,
  HRE_NOTIFY_STATUS_DESC CLOB DEFAULT NULL
);

CREATE UNIQUE INDEX UDX_HRE_NOTIFY ON HRE_NOTIFY(HRE_NOTIFY_ID);
CREATE UNIQUE INDEX UDX_HRE_NOTIFY_USER_TEMPLATE_TIMESTAMP ON HRE_NOTIFY (
  HRE_NOTIFY_USER_ID,
  HRE_NOTIFY_TEMPLATE,
  HRE_NOTIFY_TIMESTAMP
);
CREATE INDEX IDX_HRE_NOTIFY_TIMESTAMP ON HRE_NOTIFY(HRE_NOTIFY_TIMESTAMP);
CREATE BITMAP INDEX IDX_HRE_NOTIFY_TEMPLATE ON HRE_NOTIFY(HRE_NOTIFY_TEMPLATE);
CREATE BITMAP INDEX IDX_HRE_NOTIFY_STATUS_CODE ON HRE_NOTIFY(HRE_NOTIFY_STATUS_CODE);

QUIT;
