DROP TABLE HRE_NOTIFY_LOG;

CREATE TABLE HRE_NOTIFY_LOG (
  HRE_NOTIFY_LOG_SEQNUM    NUMBER(20,0) UNSIGNED NOT NULL,
  HRE_NOTIFY_LOG_ID        VARCHAR2(36) NOT NULL,
  HRE_NOTIFY_LOG_TIMESTAMP DATE NOT NULL
);

CREATE UNIQUE INDEX UDX_HRE_NOTIFY_LOG ON HRE_NOTIFY_LOG (HRE_NOTIFY_LOG_SEQNUM);
CREATE INDEX IDX_HRE_NOTIFY_LOG_ID ON HRE_NOTIFY_LOG (
  HRE_NOTIFY_LOG_ID,
  HRE_NOTIFY_LOG_TIMESTAMP,
  HRE_NOTIFY_LOG_SEQNUM
);
CREATE INDEX IDX_HRE_NOTIFY_LOG_TIMESTAMP ON HRE_NOTIFY_LOG (HRE_NOTIFY_LOG_TIMESTAMP);

CREATE SEQUENCE HRE_NOTIFY_LOG_SEQ START WITH 100000 INCREMENT BY 1 NOCACHE NOCYCLE;

QUIT;
